### ISSUE TITLE
Some issues with custom data

### ISSUE THREAD

**Issue by niclasclassen** [ajaykv1/Domain-Similarity-CDR#1]
First, I would like to thank you for having your code open source :)
I tried to use the code with custom data and found some issues:

1. action_tags_file and adventure_tags_file are no valid variables in custom_domain_embedding_similarities.py
2. Comments should be generic for custom data (e.g. Loading Movielens Glove Embeddings -> Loading Custom Glove Embeddings in  custom_domain_embedding_similarities.py)
3. `git lfs pull` results in: "This repository is over its data quota." (maybe link to data sources instead)

However, I managed to run your code after some small adjustments.

**Comment by ajaykv1** [comment]
Hi, thanks for letting me know! Glad you were able to run it!
